### ISSUE TITLE
urllib3 or chardet, not supported side package

### ISSUE THREAD

**Issue by cguentherTUChemnitz** [Tecnativa/docker-duplicity#12]
Everytime i run something in tecnativa/duplicity:docker, i get the following warning:

```
/usr/local/lib/python2.7/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.2) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
```

**Comment by Yajo** [comment]
Yes, I noticed that, although you should open the issue against upstream Duplicity project itself.

The warning means duplicity is using a deprecated method, and they should fix that.

Go https://launchpad.net/duplicity/ to find the bug tracker.

Thanks!

**Comment by cguentherTUChemnitz** [comment]
Okay, thanks for clarification.
