### ISSUE TITLE
gpg options not settable

### ISSUE THREAD

**Issue by cguentherTUChemnitz** [Tecnativa/docker-duplicity#13]
https://bugs.launchpad.net/duplicity/+bug/503309
Regarding to this link i want to set bzip2 and its compression level, to get parallel compression to speed things up significantly.

Nevertheless, the current configuration system does not enable such functionality. When i set the following environment variable inside my docker-compose setup:
```
  OPTIONS: --allow-source-mismatch --gpg-options "--compress-algo=bzip2 --bzip2-compress-level=9"
```

The single options are still splitted up and the group of the gpg-options are not treated correctly. This results in this call:

```
Executing: ['duplicity', '--allow-source-mismatch', '--gpg-options', '"--compress-algo=bzip2', '--compress-level=9"', '--metadata-sync-mode', 'partial', '/mnt/backup/src', 'file:///mnt/backup-dest/']
```
Where duplicity answers:
```
duplicity: error: no such option: --compress-level
```

How should i escape the stuff in the OPTION environment to keeo the gpg-options correctly grouped?

**Comment by Yajo** [comment]
The problem is here: https://github.com/Tecnativa/docker-duplicity/blob/f02d4da5beb93ee7bb6ae32d59ee4d254af914ce/bin/dup#L21-L23

I guess we should think a smarter splitting algorithm. Are you able to PR?

**Comment by gdgellatly** [comment]
is this still an issue? csvreader would probably do it, delimit on space, and by default it ignores delimiters in quoted text

**Comment by Yajo** [comment]
I guess the best solution would be to use strings instead of command arrays, and then pass them to `sh -c` directly.

But yes, this issue still exists. It doesn't affect us, and nobody among the affected ones volunteered to fix it. :man_shrugging:

**Comment by Tardo** [comment]
As far as I can understand this issue is resolved since the options are passed directly as string.
