### ISSUE TITLE
[Enhncement] Timezone configuration

### ISSUE THREAD

**Issue by dw72** [Tecnativa/docker-duplicity#14]
Can you add possibility to set timezone via environment variable?

**Comment by Yajo** [comment]
I gess it could be done, yes. PRs welcome! :wink:

**Comment by dw72** [comment]
I try add timzone support but when I try to run container using image builded myself from your repository I have:

```
C:\Work\docker-duplicity (master -> origin) 
λ docker run --rm dw72/duplicity:docker duplicity --help
': No such file or directory
```

When build image without my additions effect is the sam :(

So if you can add this to Dockerfile: 
```
ENV TZ='UTC'
RUN apk add --no-cache tzdata
```
this should be enough to add timezone support.

**Comment by Yajo** [comment]
Will do, thanks for the explanation.
