### ISSUE TITLE
Restore error

### ISSUE THREAD

**Issue by ValentinVinagre** [Tecnativa/docker-duplicity#16]
Hi,
I'm trying to perform a restore but I find this error. How I can solve this?
I'm save the backups in S3. It was working fine before.

![image](https://user-images.githubusercontent.com/22913794/63949410-a8e65900-ca7a-11e9-8b9c-3d97c4357205.png)

Thanks

**Comment by ValentinVinagre** [comment]
I think that error is related with this link:

https://bugs.launchpad.net/duplicity/+bug/1839886

**Comment by ValentinVinagre** [comment]
@Yajo in the version 0.8.0.4 this bug is fixed:
https://launchpad.net/duplicity/+milestone/0.8.04
ticket number: #1839886

I don't know if you change the version in docker-duplicity when the version is Announced in the https://launchpad.net/duplicity.

Thanks.

**Comment by Yajo** [comment]
Yes, sorry for that. Fixed in https://github.com/Tecnativa/docker-duplicity/commit/f02d4da5beb93ee7bb6ae32d59ee4d254af914ce. You'll have to wait until docker hub builds.

**Comment by ValentinVinagre** [comment]
Okay, thanks Yajo :)
