### ISSUE TITLE
Duplicity restore gets stuck

### ISSUE THREAD

**Issue by PCatinean** [Tecnativa/docker-duplicity#3]
I tried everything I could think of but for some reason when doing restore on the dev environment at any place it gets stuck at this point:

```
No orphaned or incomplete backup sets found.
Processing local manifest /root/.cache/duplicity/6e26b4812ae28d6c32e1a501a720c432/duplicity-full.20171213T175726Z.manifest (160189)
Found manifest volume 1
Found 1 volumes in manifest
Registering (mktemp) temporary file /tmp/duplicity-VshO67-tempdir/mktemp-_TnLHU-6
```

The point to easily get the test database on development to test certain things out. For this reason I've attached the backup service to the dev.yaml and try to restore the db.

Not sure if it ever happened to you but I just can't seem to uncover what's wrong.

**Comment by Yajo** [comment]
This is most likely due to wrong configuration of duplicity or S3 lifecycle rules. If you give all the configuration details I could try to help you, but AFAICS it's not related to the project, sorry 😕
