### ISSUE TITLE
Encoding Error

### ISSUE THREAD

**Issue by ClementVincent** [Tecnativa/docker-duplicity#33]
Hi,

I'm facing an encoding error when the mail is sent : 
```
 File "/etc/periodic/weekly/jobrunner", line 108, in <module>
    smtp.sendmail(from_, to, "\r\n".join(message))
  File "/usr/local/lib/python3.8/smtplib.py", line 859, in sendmail
    msg = _fix_eols(msg).encode('ascii')
UnicodeEncodeError: 'ascii' codec can't encode character '\xe9' in position 1055 
```

Is there a way to pre-encode (or remove wrong chars from the messages) before calling smtp.sendmail() ?

Thank you for your amazing job by the way ! :)

**Comment by Yajo** [comment]
Humm what is it that triggers the error?

**Comment by ClementVincent** [comment]
In this case it's the char "é" I guess. But it's the same with every char which are not in the ASCII table. 

https://stackoverflow.com/questions/56759272/how-do-i-send-an-e-mail-with-some-non-ascii-characters-in-python

**Comment by Tardo** [comment]
Mails are now sent with MimeText utf-8
