### ISSUE TITLE
Unable to restore

### ISSUE THREAD

**Issue by navarromiguel** [Tecnativa/docker-duplicity#34]
Hi, I'm trying for a week to restore an odoo backup stored in s3 bucket via docker duplicity postgres-s3 image but I'm not able to get it success...
This is the command I'm running:
`$ docker-compose -f prod.yaml exec backup restore --time "2020-06-18T02:00:19+02:00" --force`

and then I'm getting these warnings and errors:

Warning, found the following local orphaned signature files:

```
Local and Remote metadata are synchronized, no sync needed.
Last full backup date: Sun Jun 21 01:00:34 2020
Traceback (most recent call last):
  File "/usr/local/bin/duplicity", line 157, in <module>
    if u"Forced assertion for testing" in util.uexc(e):
  File "/usr/local/lib/python2.7/site-packages/duplicity/util.py", line 126, in uexc
    return fsdecode(m)
  File "/usr/local/lib/python2.7/site-packages/duplicity/util.py", line 74, in fsdecode
    return bytes_filename.decode(globals.fsencoding, u"replace")
AttributeError: 'int' object has no attribute 'decode'
```

What I'm doing wrong?
Thanks a lot in advance,

**Comment by Yajo** [comment]
Please update your image and retry.
