### ISSUE TITLE
Which datetime uses to execute the CRON JOB?

### ISSUE THREAD

**Issue by carlosecv** [Tecnativa/docker-duplicity#36]
Hello

Im using copier doodba 

Question: Which date time use for execute the cron:

System time
Docker container odoo
Docker container postgres

Regards

**Comment by Yajo** [comment]
I'd say it's UTC, but TBH it's something that I don't remember right now... :thinking:

**Comment by gdgellatly** [comment]
It isn't, it is set in ENV VAR `BACKUP_TZ`

**Comment by Tardo** [comment]
The CRON job is executed by the backup service using "UTC" timezone by default (when uses doodba-copier-template)

You can see the time used with: `docker-compose exec backup date`
I you want use the "host system" time... you can 'mount' `/etc/timezone` of the host in the container.
