### ISSUE TITLE
Question / Its possible to restore this files  outside copier container on different device?

### ISSUE THREAD

**Issue by carlosecv** [Tecnativa/docker-duplicity#37]
Im starting to get a lighut out how this works.

I did succesfully make an S3 backup from my copier instance so now i have multiple files created on S3 bucket from my copier project.

Now I see the commands to do a restore on the copier instance but:

¿What if i need to restore my files outside this container?

Sample: filestore and postgresql restore as dump and file tar to make inspetions on my lap?

¿Is there a way?

Regards

**Comment by Yajo** [comment]
Yes, you just mount a volume from the host in the container, then restore.

**Comment by carlosecv** [comment]
It cannot be done outside a container?
