### ISSUE TITLE
Raspberry Pi 4 Support

### ISSUE THREAD

**Issue by fracture-point** [Tecnativa/docker-duplicity#38]
Trying to bring this up on a Pi4 Raspbian install (32-bit ARM v8) I get the following error:

standard_init_linux.go:211: exec user process caused "exec format error"

I believe that this image should work, given the architecture support in the base image of python:2-alpine.

Is this just a tagging issue, or would we need to build from a different base image?

**Comment by fracture-point** [comment]
Just kidding - I had not noticed that the DockerHub build was 7+ months old.  I built the image locally using the latest dockerfile from github, and this works on 32-bit ARM.

**Comment by Yajo** [comment]
I'd like to see this upstream though, let me reopen.

**Comment by fracture-point** [comment]
@Yajo If you'd like to see how I did this in my fork, check out `.github/workflows/hub-build.yaml` - I built + deployed last night to a pi4 via dockerhub, and it works 👌.  It's a multiarch build using buildx, which appears to be the cleanest way to get this done (DockerHub multiarch automated builds still aren't there yet).

**Comment by Yajo** [comment]
If you've done the job, what if you open a PR here and then I can review it?

**Comment by fracture-point** [comment]
Might be a little clunky, since my build process is different, but I'll have a stab at it this week

**Comment by juriansluiman** [comment]
@fracture-point did you got any further?

I ran into the same issue, I'd prefer to have the multiarch build into the 'upstream' repo from Tecnative. Lately I getting more into Docker multi builds issues, if there's anything I could do (hopefully with a little guidance) please let me know.

**Comment by fracture-point** [comment]
@juriansluiman I have swapped out Duplicity in favor of Duplicati, so I didn't submit a PR....but my code is still out there (and works) in my fork at https://github.com/fracture-point/docker-duplicity/blob/master/.github/workflows/hub-build.yaml
