### ISSUE TITLE
Update docker hub link

### ISSUE THREAD

**Issue by pchampio** [Tecnativa/docker-duplicity#51]
The links in the readme are pointing to https://hub.docker.com/r/tecnativa/duplicity/ instead of https://hub.docker.com/r/tecnativa/docker-duplicity
Adding a migration notice form `tecnativa/duplicity` to `tecnativa/docker-duplicity` in https://hub.docker.com/r/tecnativa/duplicity/ could also help.

**Comment by joao-p-marques** [comment]
Right, thanks for the warning!

**Comment by joao-p-marques** [comment]
@Yajo can you do this?

**Comment by Yajo** [comment]
This can be done while moving to ghcr.
