### ISSUE TITLE
Dropbox version incompatibility

### ISSUE THREAD

**Issue by Calculagator** [Tecnativa/docker-duplicity#55]
I'm trying to use this with dropbox. I believe the dropbox-sdk-python version (8.3.1) specified in requirments.txt is either incompatible with python > 3.7 or dropbox itself. I get python syntax errors when I try to access dropbox with the image.
I think this issue was fixed in version 9 of the dropbox-sdk if I'm reading [https://github.com/dropbox/dropbox-sdk-python/issues/145](url) correctly.
I was able to work around this by forcing a dropbox version update. This may have broken some dependencies with other packages I don't use.  I don't know much about handling dependencies in python. Would it be possible to update the dropbox version in this image?

**Comment by joao-p-marques** [comment]
Thanks for reporting the issue! 
We just had a big issue with the new python pip resolver, which disallows having conflicting dependencies between the packages, so it is very possible that an update breaks that.
You can try to update the dependency using poetry (the python dependency manager we are currently using to develop) following the steps [here](https://github.com/Tecnativa/docker-duplicity/issues/26#issuecomment-768861947) (soon to be added to the docs) and see if it breaks anything or not. If you manage to find a correct "dependency alignment" to support that, feel free to report the result here or open a PR with your solution.

**Comment by derickson2402** [comment]
I am also having issues with Dropbox. I do not really know how to help solve this problem but I would love to try! Also it would be great to know if someone else figures this out.

Here is the full output from running ```/etc/periodic/daily/jobrunner``` on image ```c1ddd88d64ca``` in order to test the backup:

```plaintext
INFO:jobrunner:2021-04-17 05:12:03.106557 UTC - Running daily jobs
INFO:jobrunner:Running job 300: `backup`
ERROR:jobrunner:Failed!
Traceback (most recent call last):
  File "/etc/periodic/daily/jobrunner", line 59, in <module>
    result = check_output(expanded_command, stderr=STDOUT, shell=True, text=True)
  File "/usr/local/lib/python3.9/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/local/lib/python3.9/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'backup' returned non-zero exit status 30.
ERROR:jobrunner:
===================================
Job 300: `backup`
Started: 2021-04-17 05:12:03.107201
Finished: 2021-04-17 05:12:03.441835
Success: False

Command 'backup' returned non-zero exit status 30.
+ exec dup /srv/duplicity dpbx://skynet-archive
Traceback (innermost last):
  File "/usr/local/bin/duplicity", line 117, in <module>
    with_tempdir(main)
  File "/usr/local/bin/duplicity", line 103, in with_tempdir
    fn()
  File "/usr/local/lib/python3.9/site-packages/duplicity/dup_main.py", line 1522, in main
    action = commandline.ProcessCommandLine(sys.argv[1:])
  File "/usr/local/lib/python3.9/site-packages/duplicity/commandline.py", line 1200, in ProcessCommandLine
    backup, local_pathname = set_backend(args[0], args[1])
  File "/usr/local/lib/python3.9/site-packages/duplicity/commandline.py", line 1071, in set_backend
    config.backend = backend.get_backend(bend)
  File "/usr/local/lib/python3.9/site-packages/duplicity/backend.py", line 223, in get_backend
    obj = get_backend_object(url_string)
  File "/usr/local/lib/python3.9/site-packages/duplicity/backend.py", line 209, in get_backend_object
    return factory(pu)
  File "/usr/local/lib/python3.9/site-packages/duplicity/backends/dpbxbackend.py", line 106, in __init__
    from dropbox import Dropbox
  File "/usr/local/lib/python3.9/site-packages/dropbox/__init__.py", line 3, in <module>
    from .dropbox import __version__, Dropbox, DropboxTeam, create_session  # noqa: F401
  File "/usr/local/lib/python3.9/site-packages/dropbox/dropbox.py", line 20, in <module>
    from . import files, stone_serializers
  File "/usr/local/lib/python3.9/site-packages/dropbox/files.py", line 20
    async,
    ^
 SyntaxError: invalid syntax


INFO:jobrunner:Finished
At least one job failed
```

**Comment by joao-p-marques** [comment]
Thanks for the insight @derickson2402 

It seems that something in the dropbox Python sdk is not compatible with Python 3.9 syntax, AFAICS they only officially support up to Python 3.8

Maybe you can open an issue there and see if they can help?

If, OTOH, the problem is with incompatible dependencies here, you can try different versions of them using `poetry` following the steps from https://github.com/Tecnativa/docker-duplicity#managing-packages

**Comment by derickson2402** [comment]
Hello,

I do not have the time or knowhow to fix this issue, although I would love to see someone tackle it.

After watching [this video](https://youtu.be/y2F0wjoKEhg), I was inspired to use Google Drive since I do have an unlimited storage plan. It worked well in my preliminary testing, and was not too difficult to get working. If anyone is interested, I can link my own repository which has some basic setup information for this to work.

Thank you all for your help!
