### ISSUE TITLE
Image size cargo

### ISSUE THREAD

**Issue by pchampio** [Tecnativa/docker-duplicity#63]
With the latest update, cargo was added as a build deps.
https://github.com/Tecnativa/docker-duplicity/blob/222e6a160555a116ff39d761883c90c1df79a79a/Dockerfile#L59-L70
Could you also run `&& rm -rf /root/.cargo/` so that the image size isn't twice as big as it was before ? (+235.4MiB with the last update)

**Comment by joao-p-marques** [comment]
Thanks for the pointer and warning @pchampio 

Indeed, we remove the install dir with `apk del .build`, but there was still a lot of data left over from the installation process.
