### ISSUE TITLE
Duplicate process handling for very long backup

### ISSUE THREAD

**Issue by derickson2402** [Tecnativa/docker-duplicity#67]
Hello, I have finally tested and set up my backup solution, and I am preparing to run the first backup. However, with my pitifully slow upload speed (15mbps with Xfinity), the first upload will take around a full week.

I am fine with this, but I want to know if Duplicity will handle this correctly. Of course there will be multiple daily backups which attempt to run while the backup is going, but will Duplicity know not to run these?

**Comment by joao-p-marques** [comment]
Hi @derickson2402 

Well, we are only packaging duplicity in a cron runner, so I guess this would be a better question to ask upstream: https://gitlab.com/duplicity/duplicity

OTOH, if you want to skip the crons until you have the first full backup completed, you can override the default `JOB_*` variables and only run the command you need for the first backup, and then re-enable them when it is completed, although perhaps @Yajo could help more here.

**Comment by derickson2402** [comment]
Thanks @joao-p-marques. I ended up just running the container through a bash script rather than compose which I was using, and executed the jobrunner instead of letting cron run. This worked pretty well other than the fact that the packaged version of pydrive is broken.

**Comment by joao-p-marques** [comment]
I am glad it worked well :+1: 

> This worked pretty well other than the fact that the packaged version of pydrive is broken.

Well, we did have to loose some dependencies to make it work due to the new pip dependency resolver, so this must be a side effect. You can open a separate issue for than if you want, and maybe someone in the community wants to try to solve it :smiley:
