### ISSUE TITLE
Is it possible to run remove-older-than through to duplicity

### ISSUE THREAD

**Issue by sorvis** [Tecnativa/docker-duplicity#688]
I tried running this to see if it would work to clean up the older backups, but see it fails. Would there be an environment variable or something that would support configuring this?

```
docker-compose exec backup duplicity remove-older-than 1Y
Command line error: Expected 1 args, got 0
Enter 'duplicity --help' for help screen.
```

**Comment by pedrobaeza** [comment]
You are executing directly duplicity, so you should put the proper duplicity syntax. I think you are missing the target destination.

Closing, as this is not related to this project itself.
