### ISSUE TITLE
Feature request: support healthchecks

### ISSUE THREAD

**Issue by kaysond** [Tecnativa/docker-duplicity#694]
It would be really great if the image supported healthchecks. It would be as easy as setting a URL in an env var, then sending a request to it in the `backup` or `dup` script. I can make a PR if you'd like!

**Comment by pedrobaeza** [comment]
Yes, please do the PR.

**Comment by kaysond** [comment]
Closed in #699

**Comment by kaysond** [comment]
@pedrobaeza would you mind please doing another release so this code gets into the image?

**Comment by pedrobaeza** [comment]
Done
